### ISSUE TITLE
Use OAuth

### ISSUE THREAD

**Issue by doherty** [ghedo/p5-Dist-Zilla-Plugin-GitHub#11]
Now that logging in with a token is deprecated, you should use OAuth instead of requiring a password be stored in git's configuration.

**Comment by karenetheridge** [comment]
can this issue be closed or is there still more work to be done?

**Comment by ghedo** [comment]
Yeah, I think it can be closed. If I understandd things correctly, there's no need for oauth anymore given the Config::Identity and the token authentication support.
