### ISSUE TITLE
got an error; don't know what the problem was

### ISSUE THREAD

**Issue by karenetheridge** [ghedo/p5-Dist-Zilla-Plugin-GitHub#32]
During release:

    [@Author::ETHER/GitHub::Update] Updating GitHub repository info
    [@Author::ETHER/GitHub::Update] Using MetaCPAN URL
    [@Author::ETHER/GitHub::Update] Err:  Not Found

The repository in question is https://github.com/Leont/dist-zilla-plugin-test-checkdeps

The exact config being used is:

    [GitHub::Update]
    metacpan = 1

I'm not sure what the problem was, or how it can be remedied?  If there is a permissions issue (because I am a contributor to leont's repo, rather than me being the owner), it would be helpful for that to be in the error message, so I can drop the use of the plugin for this dist.

**Comment by autarch** [comment]
I'm getting this too, but hte problem seems to be that HTTP::Tiny is returning a hash, not a JSON blob of text.

I note that the _check_response method in Plugin ignore the value of the exception in the catch sub. It might be useful to output that.

But I'm trying to figure out why HTTP::Tiny is returning what appears to be the already-decoded JSON structure.

**Comment by autarch** [comment]
Oh, I see, HTTP::Tiny returns a hash, but content is undecoded. I'll investigate further, apparently the JSON module is unhappy with the JSON GitHub is returning here.

**Comment by karenetheridge** [comment]
Oh yes, I meant to come back to this ticket and note that I still get the "Err:  Not Found" response when releasing to *any* repository that doesn't belong to my own user account -- e.g. something in the moose org, or a repo belonging to another user -- so I wonder if the wrong API is being used?

**Comment by autarch** [comment]
@karenetheridge - I think *all* queries were broken by your last patch - see #45

This distro could really use some tests, although I'm sure writing them would be a bit of a pain with the mocking it'd require.

**Comment by karenetheridge** [comment]
It does seem to work some of the time - the last time I minted a new dist, on the first release I did see the repo metadata get updated with the ABSTRACT. But I'll take a look - it should be possible to write some tests for this - I think this is the first time I've had a need for an HTTP::Tiny equivalent to Test::LWP::UserAgent :)

**Comment by ghedo** [comment]
@autarch @karenetheridge So, here's the thing. I haven't done any real Perl development in a while and probably won't any time soon (not sure if it's just a phase...). I've tried to keep up with pull requests and such but I'm not really much interested anymore and it seems I'm not doing a very good job (e.g. I didn't properly test #44, which caused #45), so if any of you is interest in adopting this module and continuing development that would be nice (FWIW, except for FFI::Raw, my other Perl stuff is up for grabs too), otherwise it's gonna take me some time to look into any issue.

**Comment by autarch** [comment]
@ghedo - If you give @karenetheridge and I maint on the module I'm sure we can figure something out.

**Comment by karenetheridge** [comment]
Yep, I'm looking at this tonight -- since I broke it, I should fix it :)

**Comment by karenetheridge** [comment]
> Yep, I'm looking at this tonight -- since I broke it, I should fix it :)

Naturally I wrote that just *before* seeing PR #45 :)

**Comment by ghedo** [comment]
Ok, so I made both @autarch and @karenetheridge collaborators to this repo, and co-maintainers on CPAN (I hope I got the PAUSE user names right).

I'm also willing to give up primary maintainership and transfer this repo to someone else if you pick someone of you, as long as I'm kept as collaborator here on github and cpan (it's really just pro forma... I'd like to keep track of things).

**Comment by karenetheridge** [comment]
awesome, thanks! I merged #45 and released as v0.40, which should get us unstuck.  I'd be happy to take on a more serious adoption of this module, but I thought it was more important to get the fix out first.

I'm closing this ticket as it's now drifted *way* off of its original intent. :)
thanks again!

**Comment by karenetheridge** [comment]
oops, looks like I'm still missing comaint on:
Dist::Zilla::App::Command::gh
Dist::Zilla::PluginBundle::GitHub

(see the results at Dist::Zilla::PluginBundle::GitHub)

**Comment by ghedo** [comment]
Dammit, I knew I missed something. Should be fixed now.
