### ISSUE TITLE
HTTP authentication method will expire soon

### ISSUE THREAD

**Issue by sdondley** [ghedo/p5-Dist-Zilla-Plugin-GitHub#61]
I created a new local distribution and received the following email from github:

```
You recently used a password to access an endpoint through the GitHub API using HTTP-Tiny/0.056_001. We will deprecate basic authentication using password to this endpoint soon:

https://api.github.com/user/repos

We recommend using a personal access token (PAT) with the appropriate scope to access this endpoint instead. Visit https://github.com/settings/tokens for more information.

Thanks,
The GitHub Team
```

**Comment by karenetheridge** [comment]
This plugin already supports personal access tokens, so you just need to switch to using them.
Please give it a try and let me know how it goes.

**Comment by sdondley** [comment]
Ok cool. Do you have a link to the documentation for that? Maybe I’m looking at wrong distro on CPAN.

**Comment by karenetheridge** [comment]
it's at https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line .

Just store this token in the `github.password` git config.
